In [14]:
import torch
import numpy as np
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is **not available**")

GPU is available


In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.8754, 0.3333],
        [0.9840, 0.0850]])

In [10]:
x_zeros = torch.zeros(x_ones.shape)
x_zeros

tensor([[0., 0.],
        [0., 0.]])

In [12]:
tensor = x_rand

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0
